### ISSUE TITLE
Challenge an opponent

### ISSUE THREAD

**Issue by ctsstc** [ctsstc/Car-Captor#37]
Who will win?

## Grooming Required
- Is it the full garage vs another user's garage?
- Is it just a car vs a car? I think this might already be implemented.

## Post Groom't Acceptance 

- [x] A new view will present a dropdown to select two different users
- [x] A user should not be able to challenge themselves
- [ ] A winner will be based off of a user's garage's accumulated coolness value

**Comment by abell95** [comment]
I figure you can list garages with their 'coolness' values listed for comparison

Maybe you can request a head to head with another user, in the sense that it displays what cars they have that you don't and vice versa, and how it affects the final coolness score

**Comment by ctsstc** [comment]
LGTM™
